sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_install:
  - npm i -g npm@^5.8.0
before_script:
  - npm prune
script:
  - npm run test
  - npm run build
branches:
  except:
    - /^v\d+\.\d+\.\d+$/

notifications:
    webhooks: https://travis-for-jira-prod.toolsplus.app/travis/notifications?token=953bbed3-b47a-334a-bc12-c3d4794bb988
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
